# VoidRunner Development Overrides
# Extends base docker-compose.yml with development-specific settings

services:
  postgres:
    container_name: voidrunner-postgres-dev
    environment:
      POSTGRES_DB: voidrunner_dev
      POSTGRES_USER: voidrunner
      POSTGRES_PASSWORD: voidrunner_dev_password
    networks:
      - voidrunner-backend
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

  redis:
    container_name: voidrunner-redis-dev
    command: redis-server --appendonly yes  # Remove memory limits for dev
    networks:
      - voidrunner-backend
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.05'

  api:
    container_name: voidrunner-api-dev
    build:
      target: development
    environment:
      # Development Environment
      SERVER_ENV: development
      
      # Database (Development)
      DB_HOST: postgres
      DB_USER: voidrunner
      DB_PASSWORD: voidrunner_dev_password
      DB_NAME: voidrunner_dev
      DB_SSL_MODE: disable
      
      # Redis Configuration (Development)
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      REDIS_DATABASE: "0"
      
      # Queue Configuration (Development)
      QUEUE_TASK_QUEUE_NAME: "voidrunner:tasks:dev"
      QUEUE_RETRY_QUEUE_NAME: "voidrunner:tasks:retry:dev"
      QUEUE_DEAD_LETTER_QUEUE_NAME: "voidrunner:tasks:dead:dev"
      
      # Development Worker Settings
      WORKER_POOL_SIZE: "2"
      WORKER_MAX_CONCURRENT_TASKS: "10"
      WORKER_MAX_USER_CONCURRENT_TASKS: "3"
      WORKER_TASK_TIMEOUT: "5m"
      
      # Development Executor Settings (Relaxed Security)
      EXECUTOR_DEFAULT_MEMORY_LIMIT_MB: "256"
      EXECUTOR_DEFAULT_CPU_QUOTA: "50000"
      EXECUTOR_DEFAULT_TIMEOUT_SECONDS: "300"
      EXECUTOR_ENABLE_SECCOMP: "false"  # Disabled for easier development
      
      # Development Logging
      LOG_LEVEL: debug
      LOG_FORMAT: console
      
      # Development JWT (Insecure)
      JWT_SECRET_KEY: "development-secret-key-change-in-production"
      
      # Development CORS (Permissive)
      CORS_ALLOWED_ORIGINS: "*"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/app/logs
      # Add source code mounting for live development (if using air)
      - .:/app/src:ro
    
    networks:
      - voidrunner-backend
    
    restart: unless-stopped
    
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  voidrunner-backend:
    driver: bridge
