services:
  postgres-test:
    image: postgres:17-alpine
    container_name: voidrunner-test-db
    environment:
      POSTGRES_DB: voidrunner_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS:---encoding=UTF8 --lc-collate=C --lc-ctype=C}
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d voidrunner_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - voidrunner-test
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

  redis-test:
    image: redis:7-alpine
    container_name: voidrunner-test-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --maxmemory ${REDIS_MAX_MEMORY:-256mb} --maxmemory-policy allkeys-lru
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - voidrunner-test
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.05'

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local

networks:
  voidrunner-test:
    driver: bridge
